package main

import (
	"dreamers/routers"

	_ "github.com/jinzhu/gorm/dialects/sqlite"

	echoSwagger "github.com/swaggo/echo-swagger" // echo-swagger middleware

	_ "dreamers/docs" // docs is generated by Swag CLI, you have to import it.
)

// @title Dreamers API
// @version 1.0
// @description A poetic web experience where visitors send anonymous stories to the stars. Built with Echo framework in Go, Dreamers displays a night sky where stars hold personal narratives. Each page refresh repositions the stars randomly, creating a celestial sanctuary for shared stories that can only be discovered by chance—your stories remain safely hidden among the stars.
// @termsOfService http://swagger.io/terms/

// @contact.name API Support
// @contact.url http://www.swagger.io/support
// @contact.email support@swagger.io

// @host localhost:9013
// @BasePath /

func main() {
	e := routers.New()

	e.GET("/swagger/*", echoSwagger.WrapHandler)

	// run server
	e.Logger.Fatal(e.Start(":9013"))
}
